[package]
name = "rvpn"
version = "0.1.0"
authors = ["yamakaky"]

[dependencies]
error-chain = "0.7"
futures = "0.1"
mio = "0.6"
tokio-core = "0.1"
tun = { git = "git://github.com/Yamakaky/tun-rs.git" }
